# Generated by Django 3.1.5 on 2021-01-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
